language: objective-c
branches:
  only:
    master
install:
  - bundle install
  - pod repo update --silent
  - pod install
script:
  - xctool test -workspace DeepLinkKit.xcworkspace -scheme ReceiverDemo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
after_success:
  - slather
