language: objective-c
branches:
  only:
    master
before_install:
  - bundle
  - pod repo update --silent
  - pod install
script:
  - xctool test -workspace DeepLinkKit.xcworkspace -scheme ReceiverDemo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
after_success:
  - slather
